spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///rfid?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456


logging:
  level:
    root: info
    org.chen.java.mapper.security: trace
  pattern:
    console: '%p%m%n'
